### ISSUE TITLE
Type of parameter should be in next line

### ISSUE THREAD

**Issue by TimonRey** [commercetools/commercetools-docs-kit#730] opened 2020-10-27 08:12 UTC
This is already the case in all parameter tables which aren't wrapped in a method card.
here an example page:
https://docs.commercetools.com/import-api/product

How it should not look
<img width="798" alt="Bildschirmfoto 2020-10-27 um 08 50 01" src="https://user-images.githubusercontent.com/31767369/97271863-690f3300-1831-11eb-9dd2-7a34f6774d79.png">

How it should look
<img width="1006" alt="Bildschirmfoto 2020-10-27 um 09 08 18" src="https://user-images.githubusercontent.com/31767369/97274013-58ac8780-1834-11eb-924f-1c14fdeca6b9.png">

**Comment by nkuehn** [comment] 2020-10-28 19:57
@TimonRey  This is a voluntary deviation from the design that I did based on 

1. user feedback that the API endpoint layout is not compact enough to actually understand an endpoint without a lot of scrolling, which was considered a usability regression
2. The problem with the design (screenshot you pasted) is that the situation does never occur in the implementation.  The API endpoints are implemented in a way that _never_ shows the body payload type inline in the endpoint background block.  What you see in the implementation are not payload JSON types but URL path and query parameter types, which are a different thing with different expressivity.  E.g. they can never be a complex type like  "Array of ProductImport", they can only be String or Number (we don't actually use boolean parameters in our APIs).   *I think it's even a good thing to have visually different representation of these two different sorts of "data type" which are not comparable among each other*. 

@Shecki  I believe we need to groom this - if you are not happy with the look it has now you need to first update the designs with real-world data and use cases.  Typical real-word data is e.g. https://docs.commercetools.com/import-api/price#get-importoperations-by-an-importsink-key  

I can imagine "cleaner" variants but am not a fan of using the same layout as for response data types.  Technically I could have known that in the initial design process, but to be honest I did not fully  understand the implications too at the time and the decision to never render response types inline in the endpoint was never really fed back to you to check what implications it has.

**Comment by TimonRey** [comment] 2020-10-28 20:04
@nkuehn Hmm I understand...I'll leave that to you and @Shecki 👍

**Comment by Shecki** [comment] 2020-10-29 07:19
its fine for me to have it on the right side.
but should then be consistent everywhere.

this appeared because it is a mix in many different places.

**Comment by nkuehn** [comment] 2020-10-29 14:47
@Shecki I don't know of other places than the API endpoint query and path parameters where this layout is used.    All other places are body payload JSON types  (sorry, this is likely still very confusing).

**Comment by nkuehn** [comment] 2020-10-30 08:20
closing for now after a 1:1 conversation.  We'll monitor and wait for feedback.

**Closed by nkuehn** 2020-10-30 08:20 UTC
Labels: 💅 Type: Enhancement
