### ISSUE TITLE
Link manually documented common types from RAML generated type documentation

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#864] opened 2021-02-12 09:10 UTC
Both Change History and Import API sometimes use the common data types defined in the HTTP API ( https://docs.commercetools.com/api/types ). For example, LocalizedString:

<img width="1019" alt="Screenshot 2021-02-12 at 10 03 43" src="https://user-images.githubusercontent.com/63338357/107748592-99fc7080-6d19-11eb-9ef2-92a1e32a12a7.png">

Just like CategoryKeyReference above, **we want to enable a link for LocalizedString.** Currently to do so, we need to document Localized String, in this case, in the Import API micro-site. However, we prefer not to do so for the types already documented in the HTTP API doc.

An example from Change History doc:
<img width="823" alt="Screenshot 2021-02-12 at 10 16 33" src="https://user-images.githubusercontent.com/63338357/107749786-63bff080-6d1b-11eb-8452-8199f9d2bf27.png">

**Comment by nkuehn** [comment] 2021-03-09 09:31
@TohruKohrita  could it be that this is a part (or even duplicate) of #806 ? 

it's also related to #584 

My preferred approach would be to enable the gatsby raml plugin to receive a central list of  type location fallbacks as a part of the plugin configuration (or a data file if that is not overkill).  This is about a small number of low-level types that will likely remain handwritten for long because they are rather conceptual ideas.

**Comment by TohruKohrita** [comment] 2021-03-09 15:53
> @TohruKohrita could it be that this is a part (or even duplicate) of #806 ?

Yes, sorry. This is a duplicate. 

I leave it for you to close this.

**Comment by stmeissner** [comment] 2021-03-10 09:21
Duplicate of #806

**Comment by nkuehn** [comment] 2021-03-23 08:23
reopening it to cover the scope of a manual overrides list for the common types.

**Closed** 2021-05-19 12:30 UTC
Labels: 🚀 Status: Groomed, 🚀 Type: New Feature
