### ISSUE TITLE
Strange breaks/whitespace in text

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-docs-kit#691] opened 2020-10-01 08:08 UTC
<img width="765" alt="Screenshot 2020-10-01 at 10 05 28" src="https://user-images.githubusercontent.com/2638512/94784067-e465fc00-03cd-11eb-9133-9b8dc7fcb630.png">
<img width="787" alt="Screenshot 2020-10-01 at 10 05 18" src="https://user-images.githubusercontent.com/2638512/94784074-e5972900-03cd-11eb-8c6c-797ddbabbda8.png">

A picture says more than a thousand words 😉 

I checked the markdown and didn't see anything strange.

**Comment by TimonRey** [comment] 2020-10-02 11:47
@cneijenhuis where did you take this picture?

**Comment by cneijenhuis** [comment] 2020-10-04 18:04
It's two pictures, both on the products page.

**Comment by nkuehn** [comment] 2020-10-07 18:34
Location: https://docs.commercetools.com/api/projects/products#productdraft 

I was able to reproduce: 
 * it's firefox specific (Chrome and Safari fine).
 * it's appearing in many bullet points if the content of the bullet point contains more than one manual line break
 * it does not have own DOM, box model etc.   

I would preliminarily classify it as a peculiar Firefox side issue.  We had that content with manual linebreaks inside a bullet point, too previously but some other aspect seems to have been combined now. 

A content-side "fix" is to not use manual line breaks inside natural language texts at all (not good typography anyways).  I have no idea how to drill this down to a root cause.  Not labeling it "wontfix" yet until someone else has looked into it, so "help wanted" now.

**Closed** 2022-02-14 13:46 UTC
Labels: 🌊 Resolution: Wont Fix
