### ISSUE TITLE
External links don't work within the `global banner`

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1287] opened 2022-05-03 11:33 UTC
At the moment, we use a link to the official docs.commercetools.com within the global banner in closed betas. However, this link to an "external" website does not work. It only navigates to the current URL (At the end, it's only a refresh).

After inspecting the html link, I saw that there is no href URL defined, which is causing this problem.
<img width="853" alt="Bildschirmfoto 2022-05-03 um 13 23 55" src="https://user-images.githubusercontent.com/31767369/166444574-1d4cc823-d6d2-40ea-803e-ee32c200a451.png">
 
My suspicion is that the our link component does not cover this use case.

**Comment by nkuehn** [comment] 2022-05-03 14:11
It's a feature, not a bug. But in this case the behavior is not intended. 

The kit is resolving all links with relative paths and also links to the docs.commercetools.com  domain as on-site links and removes the explicit docs.commercetools.com domain. 

This is to make sure that users are staying on the preview site even if an author has put an absolute domain link into the content.  

The banner use case is different in that it _wants_ to send people off the preview domain.   The markdown renderer does inject the normal link component there.  

If we want to disable this behavior specifically only in the banner, we need to remove the injection of the `GatsbyLink` component for `a` tags in that component.  The base component from the UI kit has a "dumb" link. 

https://github.com/commercetools/commercetools-docs-kit/blob/main/packages/gatsby-theme-docs/src/components/global-notification.js#L71    (just remove the second parameter to the markdown fragment renderer)

**Closed** 2022-05-10 09:43 UTC
Labels: 🐛 Type: Bug
