### ISSUE TITLE
Functionality of anchors on lines

### ISSUE THREAD

**Issue by naveenchkrvrthy** [commercetools/commercetools-docs-kit#1264] opened 2022-03-29 11:36 UTC
When accessing links to anchors (on lines) on a different page, we jump to the top of that page when opened from the same page. It can be said that the response is similar to that of an outdated (or broken) link. However, it seems to function as expected when the link is opened in a new tab/window. Also, when we access anchors on lines in the same page, the functionality works irrespective of whether we open in the same page, or different tab/window.

- Examples of an anchor on a line in a different page:

  - Link to `InvalidOperation` error from [Create a Cart](https://docs.commercetools.com/api/projects/carts#create-a-cart-1)
  - Link to `OutofStock` error from [Create Order from a Cart](https://docs.commercetools.com/api/projects/me-orders#create-order-from-a-cart)
  - Link to Asset `key` from [Set Asset Key](https://docs.commercetools.com/api/projects/categories#set-asset-key) update action

- Examples of an anchor on a line in the same page:

  - Link to Category `key` from `parent` field in [CategoryDraft](https://docs.commercetools.com/api/projects/categories#categorydraft)
  - Link to LineItemImportDraft `productId` from `id` field in [ProductVariantImportDraft](https://docs.commercetools.com/api/projects/orders-import#productvariantimportdraft)

**Comment by FFawzy** [comment] 2022-11-11 10:58
> anchors (on lines) 

 = inline anchor tags

**Comment by gabriele-ct** [comment] 2022-11-21 11:06
This [commit](https://github.com/commercetools/commercetools-docs/pull/2062) seems to have fixed the issue:


![Image](https://user-images.githubusercontent.com/106664971/203033522-c3ed163a-6967-4c41-a4e1-2a770cd7ddd4.png)

@naveenchkrvrthy can you please check in prod and confirm if the issue is still happening?

**Comment by gabriele-ct** [comment] 2022-11-21 14:47
Closing as for the message above

**Closed by gabriele-ct** 2022-11-21 14:47 UTC
Labels: 🐛 Type: Bug, 🚀 Status: Groomed, User: Docs
